//ACTIVE

IF
Global("I#ValygarFriendshipToBCheck","GLOBAL",0)
OR(3)
Global("I#ValygarFriendshupActive","GLOBAL",0)
Global("I#ValygarFriendshupActive","GLOBAL",1)
Global("I#ValygarFriendshupActive","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("I#ValygarFriendshipToBCheck","GLOBAL",1)
SetGlobal("I#ValygarFriendshupActive","GLOBAL",2)
END

IF
Global("I#ValygarFriendshupActive","GLOBAL",2)
Global("H#ValygarRomanceActive","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("I#ValygarFriendshupActive","GLOBAL",3)
END

//Normal Relationship
//1

IF
InParty(Myself)
CombatCounter(0)
See(Player1)
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
!Global("H#ValygarRomanceActive","GLOBAL",2)
Global("I#ValygarFriendshipTalksTB","GLOBAL",0)
Global("I#ValygarFriendshupActive","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("I#ValygarFriendshipTalksTB","GLOBAL",1)
RealSetGlobalTimer("I#ValygarFriendshipTime","GLOBAL",2000)
END

IF
InParty(Myself)
CombatCounter(0)
See(Player1)
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
!AreaType(DUNGEON)
!Global("H#ValygarRomanceActive","GLOBAL",2)
Global("I#ValygarFriendshipTalksTB","GLOBAL",1)
RealGlobalTimerExpired("I#ValygarFriendshipTime","GLOBAL")
Global("I#ValygarFriendshupActive","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("I#ValygarFriendshipTalksTB","GLOBAL",2)
END

IF
Global("I#ValygarFriendshipTalksTB","GLOBAL",2)
THEN
RESPONSE #100
StartDialogue("Valyg25J",Player1)
END

//2

IF
InParty(Myself)
CombatCounter(0)
See(Player1)
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
!Global("H#ValygarRomanceActive","GLOBAL",2)
Global("I#ValygarFriendshipTalksTB","GLOBAL",3)
Global("I#ValygarFriendshupActive","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("I#ValygarFriendshipTalksTB","GLOBAL",4)
RealSetGlobalTimer("I#ValygarFriendshipTime","GLOBAL",2000)
END

IF
InParty(Myself)
CombatCounter(0)
See(Player1)
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
!Global("H#ValygarRomanceActive","GLOBAL",2)
!AreaType(DUNGEON)
Global("I#ValygarFriendshipTalksTB","GLOBAL",4)
Global("I#ValygarFriendshupActive","GLOBAL",2)
RealGlobalTimerExpired("I#ValygarFriendshipTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("I#ValygarFriendshipTalksTB","GLOBAL",5)
END

IF
Global("I#ValygarFriendshipTalksTB","GLOBAL",5)
THEN
RESPONSE #100
StartDialogue("Valyg25J",Player1)
END

//3

IF
InParty(Myself)
CombatCounter(0)
See(Player1)
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
!Global("H#ValygarRomanceActive","GLOBAL",2)
Global("I#ValygarFriendshipTalksTB","GLOBAL",6)
Global("I#ValygarFriendshupActive","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("I#ValygarFriendshipTalksTB","GLOBAL",7)
RealSetGlobalTimer("I#ValygarFriendshipTime","GLOBAL",2000)
END

IF
InParty(Myself)
CombatCounter(0)
See(Player1)
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
!Global("H#ValygarRomanceActive","GLOBAL",2)
!AreaType(DUNGEON)
Global("I#ValygarFriendshipTalksTB","GLOBAL",7)
RealGlobalTimerExpired("I#ValygarFriendshipTime","GLOBAL")
Global("I#ValygarFriendshupActive","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("I#ValygarFriendshipTalksTB","GLOBAL",8)
END

IF
Global("I#ValygarFriendshipTalksTB","GLOBAL",8)
THEN
RESPONSE #100
StartDialogue("Valyg25J",Player1)
END

//AFTER REACHING THE OUTER SENDAI ENCLAVE AREA (THE FOREST)

IF
InParty(Myself)
CombatCounter(0)
See(Player1)
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
AreaCheck("AR6100")
Global("I#ValygarFriendshipTalksSendai","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("I#ValygarFriendshipTalksSendai","GLOBAL",1)
RealSetGlobalTimer("I#ValygarSendaiTime","GLOBAL",10)
END

IF
InParty(Myself)
CombatCounter(0)
See(Player1)
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
!AreaType(DUNGEON)
Global("I#ValygarFriendshipTalksSendai","GLOBAL",1)
RealGlobalTimerExpired("I#ValygarSendaiTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("I#ValygarFriendshipTalksSendai","GLOBAL",2)
END

IF
Global("I#ValygarFriendshipTalksSendai","GLOBAL",2)
THEN
RESPONSE #100
StartDialogue("Valyg25J",Player1)
END

//SAEMON HAVARIAN

IF
InParty(Myself)
CombatCounter(0)
See(Player1)
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
OR(2)
See("AMSaemon")
GlobalGT("SaemonPlot","GLOBAL",0)
Global("I#ValygarFriendshipTalksSaemon","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("I#ValygarFriendshipTalksSaemon","GLOBAL",1)
RealSetGlobalTimer("I#ValygarSaemonTime","GLOBAL",60)
END

IF
InParty(Myself)
CombatCounter(0)
See(Player1)
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
!AreaType(DUNGEON)
Global("I#ValygarFriendshipTalksSaemon","GLOBAL",1)
RealGlobalTimerExpired("I#ValygarSaemonTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("I#ValygarFriendshipTalksSaemon","GLOBAL",2)
END

IF
Global("I#ValygarFriendshipTalksSaemon","GLOBAL",2)
THEN
RESPONSE #100
StartDialogue("Valyg25J",Player1)
END


